### PR TITLE
feat: add support for custom server links (dead + Rust borrowing errors because pain)

### PR DESCRIPTION
**Pull request by DataM0del**
yes
image

### CODE REVIEW

**Comment by DataM0del** [comment]
oops, doesn't compile lol

**Comment by DataM0del** [comment]
Fixed in 94100db

**Comment by Commandcracker** [comment]
That's why I did not add it, yeet :P
```
error[E0716]: temporary value dropped while borrowed
   --> pumpkin\src\world\mod.rs:256:39
    |
256 |                 links.push(Link::new(&Label::TextComponent(TextComponent::text_string(key.to_string())), value));
    |                 -----                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         - temporary value is freed at the end of this statement
    |                 |                     |
    |                 |                     creates a temporary value which is freed while still in use
    |                 borrow later used here
    |
    = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: could not compile `pumpkin` (bin "pumpkin") due to 1 previous error
```

**Comment by DataM0del** [comment]
I think you forgot to look at the note below it... Will add a `let` binding in a second in a second.

**Comment by DataM0del** [comment]
image

**Pull request closed without merging**
